#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-aws

# Make sure Terraform is not still running

if [ -f .terraform.tfstate.lock.info ]; then
    fail-message "Terraform is still running, please wait for it to finish."
fi

# Check state file for vnet
VNET=$(cat terraform.tfstate | jq -r '.resources[] | select(.type == "aws_subnet") | .type')

if [ "$VNET" != "aws_subnet" ]; then
  fail-message "We didn't find your aws_subnet resource. Try again."
fi

exit 0
