#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# grep -q "terraform plan" /root/.bash_history || fail-message "You haven't run terraform plan yet."

exit 0
