#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# Checks the state file to make sure the student has added a tag.
cd /root/hashicat-azure

# Needs a solve script!
# TAG=$(cat terraform.tfstate | jq -r '.resources | .[] | .instances | .[] | .attributes | .tags | .environment')

# if [ $TAG != "Production" ]; then
#   fail-message "Oops, it looks like you haven't added your Production environment tag yet."
#   exit 1
# fi