#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-azure

sed -i 's/location = var\.location/location = var.location\n\n  tags = {\n   environment = "Production"\n  }/' main.tf

exit 0
