#!/bin/bash -l

set-workdir /root/hashicat-gcp

cd /root/hashicat-gcp

# Copy the completed terraform to main.tf
cp exercises/main.tf.completed main.tf

# Just the public IP
cat <<EOF > outputs.tf
# Outputs file
output "catapp_url" {
  value = "http://\${google_compute_instance.hashicat.network_interface.0.access_config.0.nat_ip}"
}
EOF

# Run terraform init to bring in new providers
terraform init

exit 0
