version: "3"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/tfc-workstation-1-3-4
  shell: /bin/bash -l
  environment:
    CLOUD_ENV: aws
  machine_type: n1-standard-1
aws_accounts:
- name: TF-WORKSHOP
  managed_policies:
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  - arn:aws:iam::aws:policy/AmazonVPCFullAccess
  - arn:aws:iam::aws:policy/AmazonS3FullAccess
