#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# Get our TFC token and organization from the local config files
TOKEN=$(grep token /root/.terraform.d/credentials.tfrc.json | cut -d '"' -f4)

curl -s --header "Authorization: Bearer $TOKEN"   https://app.terraform.io/api/v2/organizations/$ORG/policy-sets | jq -r '.data | .[] | .attributes.name' | grep Hashicat-Social || fail-message "Uh oh, it looks like you haven't attached the Hashicat-Social policy set to your organization. Make sure you have forked the repo and added the policy set to your organization."

# We should do a run and verify that the policy check passes.

exit 0
