#!/bin/bash -l

set -e

# require-even-number.sentinel and test cases

cat <<-'EOF' > /root/sentinel/require-even-number.sentinel
# A policy that requires an integer to be even

# A parameter that must be set to an integer.
param the_number default 1

# Print the number
print("The number is:", the_number)

# The main rule
main = rule {
  # Divide the integer by 2 and compare the remainder to 0
  the_number % 2 is 0
}
EOF

mkdir -p /root/sentinel/test/require-even-number

cat <<-'EOF' > /root/sentinel/test/require-even-number/fail.json
{
  "param": {
    "the_number": <an_odd_number>
  },
  "test": {
    "main": false
  }
}
EOF

cat <<-'EOF' > /root/sentinel/test/require-even-number/pass.json
{
  "param": {
    "the_number": <an_even_number>
  },
  "test": {
    "main": true
  }
}
EOF

exit 0
