#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# grep -q "env | grep ARM_CLIENT" /root/.bash_history || fail-message "You haven't checked your Azure credentials yet."

exit 0
