#!/bin/bash -l
set -e

# Set workdir
set-workdir /root/terraform-cloud

cp -a /root/hashicat-$CLOUD_ENV/exercises/13-main.tf /root/hashicat-$CLOUD_ENV/main.tf

sed -i "s/STORAGE_MODULE/azure-backup-storage/g" /root/terraform-cloud/exercises/13-main.tf
cat /root/terraform-cloud/exercises/13-main.tf >> /root/terraform-cloud/main.tf

sed -i "s/STORAGE_MODULE/terraform-azurerm-azure-backup/g" /root/terraform-cloud/exercises/13-variables.tf
cat /root/terraform-cloud/exercises/13-variables.tf >> /root/terraform-cloud/variables.tf

sed -i "s/STORAGE_MODULE/terraform-azurerm-azure-backup/g" /root/terraform-cloud/exercises/13-terraform.tfvars
cat /root/terraform-cloud/exercises/13-terraform.tfvars >> /root/terraform-cloud/terraform.tfvars

exit 0
