#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc

# az delete resource group to clean up the elmerfudd-workshop RG if it exists.
az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
if [[ $(az group show --name elmerfudd-workshop) ]]; then
  az group delete -y --name elmerfudd-workshop
fi