#!/bin/bash

# TODO: Put an az delete resource group command in here to clean up the bugsbunny-workshop RG if it exists.
# It should not already exist or the solve scripts will fail.
# This may require installing the az command line tool on our docker image