#!/bin/bash -l

set -e

# Wait for Instruqt to finish booting the VM
# This is better than doing sleep
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

mkdir -p /root/sentinel
echo "cd /root/sentinel" >> /root/.profile

# Install Sentinel
SENTINEL_VERSION=0.24.0
wget https://releases.hashicorp.com/sentinel/${SENTINEL_VERSION}/sentinel_${SENTINEL_VERSION}_linux_amd64.zip
unzip -d /bin sentinel_${SENTINEL_VERSION}_linux_amd64.zip
rm sentinel_${SENTINEL_VERSION}_linux_amd64.zip

exit 0