#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-azure

TOKEN=$(grep token /root/.terraformrc | cut -d '"' -f2)
ORG=$(grep organization /root/hashicat-azure/remote_backend.tf | cut -d '"' -f2)

# Fetch the workspace ID
WORKSPACE_ID=$(curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json"   https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-azure | jq -r .data.id)

# Verify that virtual network exists in the modules listed in the state file
VNET_EXIST=$(curl -s --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" https://app.terraform.io/api/v2/workspaces/${WORKSPACE_ID}/current-state-version | jq '.data.attributes.modules | has("root.network")')

# Commenting out because the vnet module is broken
# TODO: Fix the vnet module or find another one.
[[ $VNET_EXIST == true ]] || fail-message "Uh oh, we couldn't find the Azure network module in your state file. Make sure you have added the azure network module to your vnet.tf file and pushed it to your remote repo."