#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-azure

# In theory, we should trigger an apply with the API, but if the first
# apply worked then we know the new one would too. 

exit 0
