#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-gcp

TOKEN=$(grep token /root/.terraform.d/credentials.tfrc.json | cut -d '"' -f4)

# Does the workspace have a placeholder variable
curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$ORG&filter%5Bworkspace%5D%5Bname%5D=hashicat-gcp" | grep -q "placeholder" || fail-message "Oh dear, it looks like you don't have a Terraform variable called 'placeholder' in your workspace. Read the notes if you need a hint on how to create this variable with the API."

# Does the workspace have a height variable
curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$ORG&filter%5Bworkspace%5D%5Bname%5D=hashicat-gcp" | grep -q "height" || fail-message "Oh dear, it looks like you don't have a Terraform variable called 'height' in your workspace. Read the notes if you need a hint on how to create this variable with the API."

# Does the workspace have a width variable
curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$ORG&filter%5Bworkspace%5D%5Bname%5D=hashicat-gcp" | grep -q "width" || fail-message "Oh dear, it looks like you don't have a Terraform variable called 'width' in your workspace. Read the notes if you need a hint on how to create this variable with the API."