#!/bin/bash -l
set -e

# Set workdir
set-workdir /root/terraform-github

# Replace the entire file. We need to do this
# in this manner as to replacethe code block for
# the TFE workspace. We can manipulate the code with
# bash but this is more straight forward.
cp -f /root/terraform-cloud/exercises/08-main.tf /root/terraform-cloud/main.tf

# Aggregate the required content 
# main.tf
cat /root/terraform-cloud/exercises/05-env_vars_main.tf >> /root/terraform-cloud/main.tf
cat /root/terraform-cloud/exercises/05-tf_vars_main.tf >> /root/terraform-cloud/main.tf
cat /root/terraform-cloud/exercises/08-users_main.tf >> /root/terraform-cloud/main.tf
cat /root/terraform-cloud/exercises/08-github_main.tf >> /root/terraform-cloud/main.tf

# Aggregate with new variables
cat /root/terraform-cloud/exercises/08-variables.tf >> /root/terraform-cloud/variables.tf

exit 0
