#!/bin/bash -l

set -e

# Clone Assets
echo "Cloning assets..."
mkdir -p /root/src/modules
git clone https://github.com/hashicorp/terraform-aws-terraform-enterprise-hvd.git /root/src/modules/terraform-aws-terraform-enterprise-hvd

exit 0
