#!/bin/bash
cd /root/hashicat-azure
source /root/.bashrc
source /etc/profile.d/instruqt-env
SERIAL=$(cat terraform.tfstate | jq .serial)

if [ $SERIAL -eq 1 ]; then
  fail-message "It looks like you haven't updated your location yet. Try again."
  exit 1
fi
