#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-azure
source /root/.bashrc
source /etc/profile.d/instruqt-env.sh

# Fails during automated test. Need to check this.
# SERIAL=$(cat terraform.tfstate | jq .serial)

# if [ $SERIAL -eq 1 ]; then
#   fail-message "It looks like you haven't updated your location yet. Try again."
#   exit 1
# fi
