#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/sentinel

# Edit the second version of the policy
sed -i 's/<expression>/else null/g' require-access-keys-use-pgp-b.sentinel
sed -i 's/<condition_1>/pgp_key is null/g' require-access-keys-use-pgp-b.sentinel
sed -i 's/<condition_2>/not strings.has_prefix(pgp_key, "keybase:")/g' require-access-keys-use-pgp-b.sentinel

# Test the second version of the policy
sentinel test -run=pgp-b.sentinel -verbose

exit 0
