#!/bin/bash -l

set -e

set-workdir /root/hashicat-azure

cd /root/hashicat-azure

#cp exercises/remote_backend.tf remote_backend.tf
cat <<-EOF > /root/hashicat-aws/remote_backend.tf

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "YOURORGANIZATION"
    workspaces {
      name = "hashicat-azure"
    }
  }
}
EOF

cat <<-EOF > /root/.terraform.d/credentials.tfrc.json
{
  "credentials": {
    "app.terraform.io": {
      "token": "YOURTOKEN"
    }
  }
}
EOF

exit 0
