#!/bin/bash
# Create the ~/.terraformrc template
cat <<-EOF > /root/.terraformrc
credentials "app.terraform.io" {
  token = "YOURTOKENHERE"
}
EOF

cd /root/hashicat-aws
cp exercises/remote_backend.tf remote_backend.tf