#!/bin/bash -l
set -e

set-workdir /root/hashicat-gcp
cd /root/hashicat-gcp

# Give the student a head start.
#cp exercises/remote_backend.tf remote_backend.tf
cat <<-EOF > /root/hashicat-gcp/remote_backend.tf

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "YOURORGANIZATION"
    workspaces {
      name = "hashicat-gcp"
    }
  }
}
EOF

mkdir -p /root/.terraform.d
cat <<-EOF > /root/.terraform.d/credentials.tfrc.json
{
  "credentials": {
    "app.terraform.io": {
      "token": "YOURTOKEN"
    }
  }
}
EOF

exit 0
