#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-aws

# Give the student a head start.
cp exercises/remote_backend.tf remote_backend.tf
cat <<-EOF > /root/.terraformrc
credentials "app.terraform.io" {
    token = "replaceme"
}
EOF