#!/bin/bash -l
# Track setup script

set -euvo pipefail

# Wait for Instruqt to finish booting the VM
# This is better than doing sleep
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Set Terraform Version
TERRAFORM_VERSION="1.1.4"

# Install desired version of Terraform
wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
mv terraform /usr/local/bin/terraform
chmod +x /usr/local/bin/terraform
rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Install cowsay
sudo apt-get update -y
sudo apt-get install -y cowsay
cp /usr/games/cowsay /usr/local/bin/cowsay

# Needed for BlastRadius
apt -y install graphviz

# Install BlastRadius in a virtualenv to get around issues with
# dependencies and system-installed versions of packages
apt -y install virtualenv
/usr/bin/virtualenv --python /usr/bin/python3 /root/venv
source /root/venv/bin/activate
pip3 install BlastRadius
# Just add /root/venv/bin to PATH so we don't force participants
# to have to activate the venv
echo "PATH=/root/venv/bin:\${PATH}" >> /root/.bashrc
echo "export PATH" >> /root/.bashrc

# Clone the hashicat-gcp repo
git clone https://github.com/hashicorp/hashicat-gcp
GITDIR="/root/hashicat-gcp"
set-workdir /root/hashicat-gcp

# Rewind everything back to a single resource group.
cd ${GITDIR}
cp ${GITDIR}/exercises/main.tf.start ${GITDIR}/main.tf
cp ${GITDIR}/exercises/outputs.tf.start ${GITDIR}/outputs.tf
mv ${GITDIR}/terraform.tfvars.example ${GITDIR}/terraform.tfvars

# Store our project ID as a Terraform env var
source /etc/profile.d/instruqt-env.sh
echo "TF_VAR_project=\"$INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID\"" >> /root/.bashrc
echo "export TF_VAR_project" >> /root/.bashrc
GOOGLE_CREDENTIALS=$(echo "$INSTRUQT_GCP_PROJECT_GCP_PROJECT_SERVICE_ACCOUNT_KEY" | base64 -d | jq 'tostring')
# Do not quote '$GOOGLE_CREDENTIALS' because `jq 'tostring'` does that for us
echo "GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS" >> /root/.bashrc
echo "export GOOGLE_CREDENTIALS" >> /root/.bashrc

exit 0
