#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-azure

# Insert an output for the catapp_ip public IP address.
cat <<-EOF >> outputs.tf

output "catapp_ip" {
  value = "http://\${azurerm_public_ip.catapp-pip.ip_address}"
}
EOF

terraform refresh

terraform output

exit 0
