#!/bin/bash
source /root/.bashrc
source /etc/profile.d/instruqt-env.sh
cd /root/hashicat-gcp

# Copy the completed terraform to main.tf
cp exercises/main.tf.completed main.tf

# # Just the public IP please
cat <<EOF > outputs.tf
# Outputs file
output "catapp_url" {
  value = "http://\${google_compute_instance.hashicat.network_interface.0.access_config.0.nat_ip}"
}
EOF

# Run terraform init to bring in new providers
terraform init
