#!/bin/bash -l
set -e

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-azure

# Students should run the 'fastforward' command to create this file.
# Otherwise it is assumed that this is a CI/CD run.
# The /root/skipconfig.json file is required for skipping challenges.
if [[ -f /root/skipconfig.json ]]; then
  ORG=$(jq -r .org < /root/skipconfig.json)
  TOKEN=$(jq -r .token < /root/skipconfig.json)
else
  ORG="instruqt-circleci"
  TOKEN=$(cat /var/tfc_user_token)
fi

# Create a workspace JSON payload with remote exec enabled
echo "Creating a workspace JSON payload..."
cat <<-EOF > /tmp/update_workspace.json
{
  "data": {
    "attributes": {
      "name": "hashicat-azure",
      "auto-apply": true,
      "execution-mode": "remote",
      "speculative-enabled": true,
      "terraform-version": "1.0.7"
    },
    "type": "workspaces"
  }
}
EOF

# Update the workspace to enable remote exec
curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request PATCH --data @/tmp/update_workspace.json https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-azure

# Fetch the workspace ID
WORKSPACE_ID=$(curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json"   https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-azure | jq -r .data.id)

# Create JSON payloads for variables
cat <<-EOF > /tmp/client_id.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"ARM_CLIENT_ID",
      "value":"$ARM_CLIENT_ID",
      "category":"env",
      "hcl":false,
      "sensitive":false
    },
    "relationships": {
      "workspace": {
        "data": {
          "id":"$WORKSPACE_ID",
          "type":"workspaces"
        }
      }
    }
  }
}
EOF

cat <<-EOF > /tmp/client_secret.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"ARM_CLIENT_SECRET",
      "value":"$ARM_CLIENT_SECRET",
      "category":"env",
      "hcl":false,
      "sensitive":true
    },
    "relationships": {
      "workspace": {
        "data": {
          "id":"$WORKSPACE_ID",
          "type":"workspaces"
        }
      }
    }
  }
}
EOF

cat <<-EOF > /tmp/tenant_id.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"ARM_TENANT_ID",
      "value":"$ARM_TENANT_ID",
      "category":"env",
      "hcl":false,
      "sensitive":false
    },
    "relationships": {
      "workspace": {
        "data": {
          "id":"$WORKSPACE_ID",
          "type":"workspaces"
        }
      }
    }
  }
}
EOF

cat <<-EOF > /tmp/subscription_id.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"ARM_SUBSCRIPTION_ID",
      "value":"$ARM_SUBSCRIPTION_ID",
      "category":"env",
      "hcl":false,
      "sensitive":false
    },
    "relationships": {
      "workspace": {
        "data": {
          "id":"$WORKSPACE_ID",
          "type":"workspaces"
        }
      }
    }
  }
}
EOF

cat <<-EOF > /tmp/prefix.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"prefix",
      "value":"$PREFIX",
      "category":"terraform",
      "hcl":false,
      "sensitive":false
    },
    "relationships": {
      "workspace": {
        "data": {
          "id":"$WORKSPACE_ID",
          "type":"workspaces"
        }
      }
    }
  }
}
EOF

cat <<-EOF > /tmp/location.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"location",
      "value":"eastus",
      "category":"terraform",
      "hcl":false,
      "sensitive":false
    },
    "relationships": {
      "workspace": {
        "data": {
          "id":"$WORKSPACE_ID",
          "type":"workspaces"
        }
      }
    }
  }
}
EOF

# Create our variables in HCP Terraform
curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request POST --data @/tmp/client_id.json https://app.terraform.io/api/v2/vars

curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request POST --data @/tmp/client_secret.json https://app.terraform.io/api/v2/vars

curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request POST --data @/tmp/tenant_id.json https://app.terraform.io/api/v2/vars

curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request POST --data @/tmp/subscription_id.json https://app.terraform.io/api/v2/vars

curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request POST --data @/tmp/prefix.json https://app.terraform.io/api/v2/vars

curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request POST --data @/tmp/location.json https://app.terraform.io/api/v2/vars

# Run remote apply
terraform apply -auto-approve

sleep 30

exit 0
