#!/bin/bash -l

set -euvo pipefail#

# Wait for Instruqt to finish booting the VM
# This is better than doing sleep
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

apt update
apt install awscli tree -y

# Source important environment variables
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
# Add AWS CLI completion
echo "export PATH=/usr/bin/:\$PATH" >> /root/.bashrc
echo "complete -C '/usr//bin/aws_completer' aws" >> /root/.bashrc

source ~/.bashrc

# Set Terraform Version
TERRAFORM_VERSION="1.11.0"

# Install desired version of Terraform
wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
mv terraform /usr/local/bin/terraform
chmod +x /usr/local/bin/terraform
rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Leaving this in for now... Will change to the built in editor at some point
#curl -fsSL https://code-server.dev/install.sh | sh
curl -fsSL https://code-server.dev/install.sh | sh -s -- --version 3.12.0

# Install Terraform Extension
code-server --install-extension hashicorp.terraform --force

# code-server config
mkdir -p /root/.local/share/code-server/User
cat <<-EOF > /root/.local/share/code-server/User/settings.json
{
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.fontFamily": "Inconsolata, Consolas, 'Courier New', monospace",
    "terminal.integrated.copyOnSelection": true
    "workbench.colorTheme": "Default Dark+"
}
EOF

# Start up Visual Studio Code server
# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/bin/code-server --bind-addr 0.0.0.0:8443 --cert --auth none /root/src
[Install]
WantedBy=multi-user.target
EOF

# Add AWS keys to systemd environment
systemctl import-environment AWS_ACCESS_KEY_ID
systemctl import-environment AWS_SECRET_ACCESS_KEY

# Start VSC
systemctl enable code-server
systemctl start code-server


echo AWS Console: https://$AWS_ACCOUNT_ID.signin.aws.amazon.com/console/
echo AWS Account Username:  $AWS_ACCOUNT_USERNAME
echo AWS Account Password:  $AWS_ACCOUNT_PASSWORD

EOF
