#!/bin/bash -l

set -e

# Run 'touch /tmp/skip-check' to disable this check
if [ -f /tmp/skip-check ]; then
  rm /tmp/skip-check
  exit 0
fi

cd /root/sentinel

grep -qL "<resource_type>" require-access-keys-use-pgp-1.sentinel && fail-message "You have not replaced '<resource_type>' in require-access-keys-use-pgp-1.sentinel yet."

grep -q "aws_iam_access_key" require-access-keys-use-pgp-1.sentinel || fail-message "You have not replaced '<resource_type>' with 'aws_iam_access_key' in require-access-keys-use-pgp-1.sentinel yet."

grep -qL "<attribute>" require-access-keys-use-pgp-1.sentinel && fail-message "You have not replaced '<attribute>' in require-access-keys-use-pgp-1.sentinel yet."

grep -q "pgp_key" require-access-keys-use-pgp-1.sentinel || fail-message "You have not replaced '<attribute>' with 'pgp_key' in require-access-keys-use-pgp-1.sentinel yet."

grep -qL "<condition>" require-access-keys-use-pgp-1.sentinel && fail-message "You have not replaced '<condition>' in require-access-keys-use-pgp-1.sentinel yet."

grep -q "violations is 0" require-access-keys-use-pgp-1.sentinel || grep -q "violations == 0" require-access-keys-use-pgp-1.sentinel || fail-message "You have not replaced '<condition>' with 'violations is 0' or 'violations == 0' in require-access-keys-use-pgp-1.sentinel yet."

grep -q "cp require-access-keys-use-pgp-1.sentinel require-access-keys-use-pgp.sentinel" /root/.bash_history || fail-message "You have not copied require-access-keys-use-pgp-1.sentinel to require-access-keys-use-pgp.sentinel yet."

grep -q "sentinel test -run=pgp.sentinel -verbose" /root/.bash_history || fail-message "You haven't tested the first version of require-access-keys-use-pgp.sentinel policy yet. Please run 'sentinel test -run=pgp.sentinel -verbose'"

grep -qL "<expression>" require-access-keys-use-pgp-1.sentinel && fail-message "You have not replaced '<expression>' in require-access-keys-use-pgp-2.sentinel yet."

grep -q "key.change.after.pgp_key else null" require-access-keys-use-pgp-2.sentinel || fail-message "You have not replaced '<expression>' with 'else null' in require-access-keys-use-pgp-2.sentinel yet."

grep -qL "<condition_1>" require-access-keys-use-pgp-1.sentinel && fail-message "You have not replaced '<condition_1>' in require-access-keys-use-pgp-2.sentinel yet."

grep -q "pgp_key is null" require-access-keys-use-pgp-2.sentinel || grep -q "pgp_key == null" require-access-keys-use-pgp-2.sentinel || fail-message "You have not replaced '<condition_1>' with 'pgp_key is null' or 'pgp_key == null' in require-access-keys-use-pgp-2.sentinel yet."

grep -qL "<condition_2>" require-access-keys-use-pgp-1.sentinel && fail-message "You have not replaced '<condition_2>' in require-access-keys-use-pgp-2.sentinel yet."

grep -q 'not strings.has_prefix(.*pgp_key.*,.*"keybase:")' require-access-keys-use-pgp-2.sentinel || fail-message "You have not replaced '<condition_2>' with 'not strings.has_prefix(pgp_key, \"keybase:\")' in require-access-keys-use-pgp-2.sentinel yet."

grep -q "cp require-access-keys-use-pgp-2.sentinel require-access-keys-use-pgp.sentinel" /root/.bash_history || fail-message "You have not copied require-access-keys-use-pgp-2.sentinel to require-access-keys-use-pgp.sentinel yet."

sentinel test -run=pgp.sentinel
rc=$?
if [ $rc -ne 0 ]; then
    fail-message "Your second version of the policy did not pass all 4 test cases. Please revise and test it again."
fi

exit 0
