#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-azure

sed -i 's/^  tags = {}/  tags = {\n   environment = "Production"\n  }/' main.tf

terraform apply -auto-approve

exit 0
