#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-azure

# Make sure Terraform is not still running

if [ -f .terraform.tfstate.lock.info ]; then
    fail-message "Terraform is still running, please wait for it to finish."
fi


# Check state file for vnet
VNET=$(cat terraform.tfstate | jq -r '.resources[] | select(.type == "azurerm_virtual_network") | .type')

if [ "$VNET" != "azurerm_virtual_network" ]; then
  fail-message "We didn't find your azurerm_virtual_network resource. Try again."
fi

exit 0
