#!/bin/bash
set -e
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc

# Allow instruqt time to do its thing
sleep 10

# Generate the Azure creds setup script
cat <<-EOF > /bin/setup_azure.sh
#!/bin/bash
# Define some colors
red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

# Fetch temporary Azure credentials from a Vault server
# Requires \$VAULT_ADDR, \$VAULT_NAMESPACE, \$VAULT_CREDS_ENDPOINT and \$VAULT_TOKEN to be set as environment variables

# Regex matching the shape of Azure credentials
AZURE_REGEX="[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}"

echo "Fetching dynamic Azure credentials from \${VAULT_ADDR}/v1/\${VAULT_CREDS_ENDPOINT}"
curl -s --retry 5 -H "X-Vault-Token: \${VAULT_TOKEN}" -H "X-Vault-Namespace: \$VAULT_NAMESPACE" \${VAULT_ADDR}/v1/\${VAULT_CREDS_ENDPOINT} | \
jq -r '[.data.client_id,.data.client_secret] | @tsv' | \
while read id secret; do
  if [[ \$id =~ \$AZURE_REGEX ]] && [[ \$secret =~ \$AZURE_REGEX ]]; then
    echo "Valid Azure credentials received. Testing them now..."
    until \$(az login --service-principal --username=\$id --password=\$secret --tenant=\$ARM_TENANT_ID > /dev/null 2>&1); do
      echo "Waiting for Azure credentials to be ready..."
      sleep 10
    done
    echo "Azure credentials are ready. Storing them as environment variables."
    echo "export ARM_CLIENT_ID=\$id" >> ~/.bashrc
    echo "export ARM_CLIENT_SECRET=\$secret" >> ~/.bashrc
  else
    echo "Error fetching Azure credentials. Please run the script again."
    exit 1
  fi
done || exit 1

echo "\${grn}Ready to run Terraform on...\${end}"
echo "${blu}"
echo '     /\'
echo '    /  \    _____   _ _  ___ _'
echo "   / /\\\ \\\  |_  / | | | \\\'__/ _\\\"
echo '  / ____ \  / /| |_| | | |  __/'
echo ' /_/    \_\/___|\__,_|_|  \___|'
echo "${end}"
echo "\${mag}Setup script complete. Your Azure credentials are valid for 8 hours.\${end}"
EOF

chmod +x /bin/setup_azure.sh
git clone https://github.com/hashicorp/hashicat-azure
GITDIR="/root/hashicat-azure"
/bin/set-workdir "${GITDIR}"

# Rewind everything back to a single resource group.
cd ${GITDIR}
mv ${GITDIR}/terraform.tfvars.example ${GITDIR}/terraform.tfvars

# Fetch dynamic creds for Azure
export VAULT_TOKEN=$(cat /var/vault_token)
/bin/setup_azure.sh

# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/local/bin/code-server --port 8443 --cert --auth none $(pwd)

[Install]
WantedBy=multi-user.target
EOF

# Start VSC
systemctl start code-server

# Back to our git repo and init
cd $GITDIR
terraform init

# Fix up the ~/.vimrc file
echo -e "let g:solarized_termcolors=256\nset t_Co=256\nsyntax enable\nset background=dark\ncolorscheme solarized" > /tmp/.vimrc
mv /tmp/.vimrc /root/.vimrc
chattr +i /root/.vimrc

# Import VAULT_TOKEN in case we need to get new creds
echo "export VAULT_TOKEN=\$(cat /var/vault_token)" >> /root/.bashrc

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc

# Drop the Terraform extension vsix file into /root
wget https://storage.googleapis.com/instruqt-hashicorp-tracks/terraform-shared/mauve.terraform-1.4.0.vsix -O /root/mauve.terraform-1.4.0.vsix
