#!/bin/bash

# Blow away the test workspace, hashicat-azure if it exists
ORG=instruqt-circleci
TOKEN=$(cat /tmp/tfc_user_token)

# Delete the workspace. Might result in a 404 but that's OK as long as curl doesn't error out.
echo "Cleaning up the hashicat-azure workspace..."
curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request DELETE https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-azure

# az delete resource group to clean up the tweetybird-workshop RG if it exists.
az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
if [[ $(az group show --name tweetybird-workshop) ]]; then
  az group delete -y --name tweetybird-workshop
fi