#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-azure

# Check state file for vnet
VNET=$(cat terraform.tfstate | jq -r '.resources[] | select(.type == "azurerm_virtual_network") | .type')

if [ $VNET != "azurerm_virtual_network" ]; then
  fail-message "We didn't find your azurerm_virtual_network resource. Try again."
fi

exit 0
