#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc

git clone --single-branch --branch instruqt https://github.com/hashicorp/hashicat-aws

# Rewind everything back to a single resource group.
GITDIR="/root/hashicat-aws"
cd ${GITDIR}
echo -e "prefix = \"workshop\"" >> ${GITDIR}/terraform.tfvars
echo -e "\nregion = \"us-west-2\"" >> ${GITDIR}/terraform.tfvars
/usr/local/bin/terraform init

/bin/set-workdir ${GITDIR}