#!/bin/bash

# Blow away the test workspace, hashicat-aws if it exists
ORG="instruqt-circleci"
TOKEN=$(cat /var/tfc_user_token)

# Store the ORG variable in /root/.bashrc
echo "export ORG=\"$ORG\"" >> /root/.bashrc

# Delete the workspace. Might result in a 404 but that's OK as long as curl doesn't error out.
echo "Cleaning up the hashicat-aws workspace..."
curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request DELETE https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-aws

# fudge the git repo for testing; this one is already completed
cd /root
rm -rf hashicat-aws
git clone https://github.com/workshops-testbot/hashicat-aws
GITDIR="/root/hashicat-aws"

cd ${GITDIR}
echo -e "prefix = \"workshop\"" >> ${GITDIR}/terraform.tfvars
echo -e "\nregion = \"us-east-1\"" >> ${GITDIR}/terraform.tfvars

# Just the public DNS please
cat <<EOF > outputs.tf
# Outputs file
output "catapp_url" {
  value = "http://\${aws_eip.hashicat.public_dns}"
}
EOF