# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "3"
virtualmachines:
- name: tfe-hvd-workstation
  image: instruqt-hashicorp/ubuntu-2004-base
  shell: /bin/bash -l
  machine_type: n1-standard-1
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  ports: [80]
  shell: /bin/bash
aws_accounts:
- name: TF-WORKSHOP
#  regions: [us-west-1]
  managed_policies:
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  - arn:aws:iam::aws:policy/AmazonVPCFullAccess
  - arn:aws:iam::aws:policy/AmazonS3FullAccess
  - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
  - arn:aws:iam::aws:policy/AmazonRDSFullAccess


