#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-gcp

# Insert an output for the catapp_ip public IP address.
cat <<-EOF >> outputs.tf

output "catapp_ip" {
  value = "http://\${google_compute_instance.hashicat.network_interface.0.network_ip}"
}
EOF

terraform refresh

terraform output

exit 0
