#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-aws

# Make sure Terraform is not still running

if [ -f .terraform.tfstate.lock.info ]; then
    fail-message "Terraform is still running, please wait for it to finish."
fi

# Ensure `catapp_url` is defined in Terraform putouts
CATAPP_URL=$(terraform output -raw catapp_url 2>/dev/null)
if [ -z "$CATAPP_URL" ]; then
    fail-message "catapp_url not defined, try provisioning it again"
fi

# Fetch the URL and grep the HTTP code for "200 OK"
# Add retries in case the website isn't up and running yet.
CATAPP_STATUS=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 60 -o /dev/null -s -w '%{http_code}' "$CATAPP_URL")
if [ "$CATAPP_STATUS" != "200" ]; then
    fail-message "We were unable to load your web app. Try provisioning it again."
fi

exit 0
