#!/bin/bash -l
set -euxvo pipefail

ORG=$(grep organization /root/terraform-cloud/terraform.tfvars | cut -d '"' -f2)
WORKSPACE=$(grep workspace /root/terraform-cloud/terraform.tfvars | cut -d '"' -f2)

agent variable set TF_ORG $ORG
agent variable set TF_WORKSPACE $WORKSPACE

cp /root/hashicat-$CLOUD_ENV/remote_backend.tf.example /root/hashicat-$CLOUD_ENV/remote_backend.tf

cd /root/hashicat-$CLOUD_ENV
sed -i "s/YOUR_ORGANIZATION/$ORG/g" remote_backend.tf
sed -i "s/YOUR_WORKSPACE/$WORKSPACE/g" remote_backend.tf

cd /root/terraform-api
sed -i "s/YOUR_ORGANIZATION/$ORG/g" terraform.tfvars.example
mv terraform.tfvars.example terraform.tfvars

# Store the ORG in /root/.bashrc
echo "export ORG=\"$ORG\"" >> /root/.bashrc

# Store the WORKSPACE in /root/.bashrc
echo "export WORKSPACE=\"$WORKSPACE\"" >> /root/.bashrc

exit 0
