#!/bin/bash -l

set -e

set-workdir /root/hashicat-aws

cd /root/hashicat-aws

cp exercises/remote_backend.tf remote_backend.tf

cat <<-EOF > /root/.terraform.d/credentials.tfrc.json
{
  "credentials": {
    "app.terraform.io": {
      "token": "YOURTOKEN"
    }
  }
}
EOF

exit 0
