#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-azure

[[ -f /usr/bin/fastforward ]] || fail-message "Uh oh, you're missing the fastforward script. Please restart your track."

exit 0
