#!/bin/bash
source /root/.bashrc
source /etc/profile.d/instruqt-env.sh
cd /root/hashicat-aws

git clone --single-branch --branch instruqt https://github.com/hashicorp/hashicat-aws

# Rewind everything back to a single resource group.
GITDIR="/root/hashicat-aws"
cd ${GITDIR}
cp ${GITDIR}/exercises/main.tf.start ${GITDIR}/main.tf
cp ${GITDIR}/exercises/outputs.tf.start ${GITDIR}/outputs.tf
mv ${GITDIR}/terraform.tfvars.example ${GITDIR}/terraform.tfvars

cd ${GITDIR}
/bin/set-workdir ${GITDIR}

terraform init