#!/bin/bash
source /root/.bashrc
source /etc/profile.d/instruqt-env.sh
cd /root/hashicat-aws

git clone https://github.com/hashicorp/hashicat-aws

# Rewind everything back to a single resource group.
GITDIR="/root/hashicat-aws"
cd ${GITDIR}
cp ${GITDIR}/exercises/main.tf.start ${GITDIR}/main.tf
cp ${GITDIR}/exercises/outputs.tf.start ${GITDIR}/outputs.tf
mv ${GITDIR}/terraform.tfvars.example ${GITDIR}/terraform.tfvars

cd ${GITDIR}
/bin/set-workdir ${GITDIR}

# Install VSC terraform extension
cd /root/.local/share/code-server/extensions/
tar -zxvf /tmp/mauve.terraform-1.4.0.tar.gz

terraform init