#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc

# Clone the hashicat-aws repo
git clone https://github.com/hashicorp/hashicat-aws
GITDIR="/root/hashicat-aws"
/bin/set-workdir "${GITDIR}"

# Rewind everything back to a single resource group.
cd ${GITDIR}
cp ${GITDIR}/exercises/main.tf.start ${GITDIR}/main.tf
cp ${GITDIR}/exercises/outputs.tf.start ${GITDIR}/outputs.tf
mv ${GITDIR}/terraform.tfvars.example ${GITDIR}/terraform.tfvars

# Start up Visual Studio Code server
# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/local/bin/code-server --port 8443 --cert --auth none $(pwd)

[Install]
WantedBy=multi-user.target
EOF

# Start VSC
systemctl start code-server

# Back to our git repo and init
cd $GITDIR
terraform init

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc