#!/bin/bash -l

set -e

mkdir -p /root/sentinel
echo "cd /root/sentinel" >> /root/.profile

# Install Sentinel
SENTINEL_VERSION=0.15.6
wget https://releases.hashicorp.com/sentinel/${SENTINEL_VERSION}/sentinel_${SENTINEL_VERSION}_linux_amd64.zip
unzip -d /bin sentinel_${SENTINEL_VERSION}_linux_amd64.zip
rm sentinel_${SENTINEL_VERSION}_linux_amd64.zip

exit 0
