#!/bin/bash -l
set -e

# Allow instruqt time to do its thing
sleep 10

# Clone the hashicat-azure repo
git clone https://github.com/hashicorp/hashicat-azure
GITDIR="/root/hashicat-azure"

# Set workdir
set-workdir /root/hashicat-azure

# Rewind everything back to a single resource group.
cd ${GITDIR}
cp ${GITDIR}/exercises/main.tf.start ${GITDIR}/main.tf
cp ${GITDIR}/exercises/outputs.tf.start ${GITDIR}/outputs.tf
mv ${GITDIR}/terraform.tfvars.example ${GITDIR}/terraform.tfvars

# Start up Visual Studio Code server
# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/bin/code-server --host 0.0.0.0 --port 8443 --cert --auth none /root/hashicat-azure

[Install]
WantedBy=multi-user.target
EOF

# Add Azure creds to systemd environment
systemctl import-environment ARM_SUBSCRIPTION_ID
systemctl import-environment ARM_TENANT_ID
systemctl import-environment ARM_CLIENT_ID
systemctl import-environment ARM_CLIENT_SECRET

# Start VSC
systemctl enable code-server
systemctl start code-server

exit 0
