#!/bin/bash -l
set -e

mkdir /root/hashicat-aws/json
set-workdir /root/hashicat-aws/json
cd /root/hashicat-aws/json

# Create some payload files for the student
for VAR in placeholder width height; do
cat <<-EOF > /root/hashicat-aws/json/var-${VAR}.json
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"${VAR}",
      "value":"REPLACE_ME",
      "category":"terraform",
      "hcl":false,
      "sensitive":false
    }
  }
}
EOF
done

# Create the payload for the plan/apply
cat <<-EOF > /root/hashicat-aws/json/apply.json
{
  "data": {
    "attributes": {
      "is-destroy":false,
      "message": "HCP Terraform API is Magic! 🦄 🌈 🧙‍♂️"
    },
    "type":"runs",
    "relationships": {
      "workspace": {
        "data": {
          "type": "workspaces",
          "id": "REPLACE_WITH_WORKSPACE_ID"
        }
      }
    }
  }
}
EOF

exit 0
