#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/sentinel

# Edit the first version of the policy
sed -i 's/<resource_type>/google_compute_instance/g' restrict-gcp-instance-image-1.sentinel
sed -i 's/<expression_1>/boot_disk.0.initialize_params.0.image/g' restrict-gcp-instance-image-1.sentinel
sed -i 's/<expression_2>/length(violatingGCPComputeInstances["messages"])/g' restrict-gcp-instance-image-1.sentinel

# Copy the first version of the policy
cp restrict-gcp-instance-image-1.sentinel restrict-gcp-instance-image.sentinel

# Test the first version of the policy
sentinel test -run=image.sentinel -verbose

# Edit the second version of the policy
sed -i 's/<expression_1>/instance.change.after.boot_disk/g' restrict-gcp-instance-image-2.sentinel
sed -i 's/<expression_2>/boot_disk[0].initialize_params/g' restrict-gcp-instance-image-2.sentinel
sed -i 's/<expression_3>/boot_disk[0].initialize_params[0].image/g' restrict-gcp-instance-image-2.sentinel
sed -i 's/<add_main_rule>/main = rule { violations is 0 }/g' restrict-gcp-instance-image-2.sentinel

# Copy the second version of the policy
cp restrict-gcp-instance-image-2.sentinel restrict-gcp-instance-image.sentinel

# Test the second version of the policy
sentinel test -run=image.sentinel -verbose

exit 0
