#!/bin/bash
source /root/.bashrc
source /etc/profile.d/instruqt-env.sh
cd /root/hashicat-aws

# Fetch the URL and grep the HTTP code for "200 OK"
curl -I $(cat terraform.tfstate | jq -r .outputs.catapp_url.value) | grep "200 OK"
EXITCODE=$?

if [ $EXITCODE -ne 0 ]; then
  fail-message "We were unable to load your web app. Try provisioning it again."
  exit 1
fi