#!/bin/bash
source /root/.bashrc
source /etc/profile.d/instruqt-env.sh
cd /root/hashicat-aws

# Copy the completed terraform to main.tf
cp exercises/main.tf.completed main.tf

# Just the public DNS please
cat <<EOF > outputs.tf
# Outputs file
output "catapp_url" {
  value = "http://\${aws_eip.hashicat.public_dns}"
}
EOF

# Run terraform init to bring in new providers
terraform init
