#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-aws

if [[ -f /root/skipconfig.json ]]; then
  ORG=$(jq -r .org < /root/skipconfig.json)
  GITUSERID=$(jq -r .gituserid < /root/skipconfig.json)
  GITPAT=$(jq -r .gitpat < /root/skipconfig.json)
  cat <<-EOF > s3-bucket.tf
module "s3-bucket" {
  source  = "app.terraform.io/$ORG/s3-bucket/aws"
  version = "2.8.0"
  bucket_prefix = var.prefix
}
EOF
  git add .
  git commit -m "Added s3 bucket module"
  cat <<-EOF > /root/.netrc
machine github.com
login $GITUSERID
password $GITPAT
EOF
  git push origin master
else
  echo "CircleCI run - no git push required."
fi

exit 0
