#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-aws

# Write out s3-bucket.tf
cat <<-EOF > s3-bucket.tf
module "s3-bucket" {
  source  = "app.terraform.io/instruqt-circleci/s3-bucket/aws"
  version = "1.15.0"
  bucket_prefix = var.prefix
}
EOF

# Students should run the 'fastforward' command to create this file.
# Otherwise it is assumed that this is a CI/CD run.
# The /root/skipconfig.json file is required for skipping challenges.
if [[ -f /root/skipconfig.json ]]; then
  ORG=$(jq -r .org < /root/skipconfig.json)
  GITUSERID=$(jq -r .gituserid < /root/skipconfig.json)
  GITPWD=$(jq -r .gitpwd < /root/skipconfig.json)
  # Set ORG in s3-bucket.tf
  sed -i "s/instruqt-circleci/$ORG/g" s3-bucket.tf
  git add .
  git commit -m "Added s3 bucket module"
  cat <<-EOF > /root/.netrc
  machine github.com
  login $GITUSERID
  password $GITPWD
EOF
  git push origin master
fi

# The above will trigger a run for students who are skipping
# In theory, we also should trigger an apply with the API for CircleCI tests,
# but if the first apply worked then we know the new one would too.

exit 0
