#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-aws
cd /root/hashicat-aws

ORG="instruqt-testing"
TOKEN=$(cat /tmp/tfc_user_token)

# TODO - write a solve script to switch to remote exec
# Curl command to change to remote exec
# Curl commands to populate environment vars
# Curl commands to populate terraform vars