#!/bin/bash -l
set -e

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Fetch a clean copy of the hashicat-gcp repo
cd /root
rm -rf hashicat-gcp

# Check if this is a student or bot run
if [[ -f /root/skipconfig.json ]]; then
  ORG=$(jq -r .org < /root/skipconfig.json)
  TOKEN=$(jq -r .token < /root/skipconfig.json)
else
  ORG="instruqt-circleci"
  TOKEN=$(cat /var/tfc_user_token)
fi
git clone https://github.com/hashicorp/hashicat-gcp

cd hashicat-gcp
mv terraform.tfvars.example terraform.tfvars
echo -e "# region = \"\"" >> terraform.tfvars
echo -e "# zone = \"\"" >> terraform.tfvars

# Store the ORG in /root/.bashrc
grep $ORG /root/.bashrc || echo "export ORG=\"$ORG\"" >> /root/.bashrc

# Delete the workspace. Might result in a 404 but that's OK as long as curl doesn't error out.
echo "Cleaning up the hashicat-gcp workspace..."
curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request DELETE https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-gcp

# Wipe the bash history
history -c

exit 0
