#!/bin/bash
cd /root/hashicat-azure
if [ ! -f terraform.tfstate ]; then
  fail-message "Oops, it looks like you haven't run terraform apply yet."
  exit 1
fi

MYRG=$(cat terraform.tfstate | jq -r '.resources | .[].name')

if [ $MYRG != "myresourcegroup" ]; then
  fail-message "It looks like your resource group has not been built yet. Please try again."
  exit 1
fi