#!/bin/bash
cd /root/hashicat-azure
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc

echo "Azure Credentials are:"
echo $ARM_SUBSCRIPTION_ID
echo $ARM_TENANT_ID
echo $ARM_CLIENT_ID
echo $ARM_CLIENT_SECRET

# Wait for Azure creds to become valid...
#echo "Sleeping"
#sleep 60

for i in {0..10}
do
  echo $ARM_CLIENT_SECRET
  if [ -z  "$ARM_CLIENT_SECRET" ]
  then
    echo "ARM_CLIENT_SECRET not set yet"
    sleep 6
  else
    echo "$ARM_CLIENT_SECRET"
    break
  fi
done

/usr/local/bin/terraform apply -auto-approve
