#!/bin/bash -l
set -e

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-gcp

if [[ -f /root/skipconfig.json ]]; then
  ORG=$(jq -r .org < /root/skipconfig.json)
  GITUSERID=$(jq -r .gituserid < /root/skipconfig.json)
  GITPAT=$(jq -r .gitpat < /root/skipconfig.json)
  cat <<-EOF > vpc.tf
module "network" {
  source  = "app.terraform.io/$ORG/network/google"
  version = "3.4.0"
  network_name = "gaurav-network"
  project_id = var.project
  subnets = [
    {
      subnet_name   = "gaurav-subnet"
      subnet_ip     = "10.100.10.0/24"
      subnet_region = var.region
    }
  ]
}
EOF
  git add .
  git commit -m "Added vpc module"
  cat <<-EOF > /root/.netrc
machine github.com
login $GITUSERID
password $GITPAT
EOF
  git push origin master
else
  echo "CircleCI run - no git push required."
fi

exit 0
