#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-aws

TOKEN=$(grep token /root/.terraformrc | cut -d '"' -f2)
ORG=$(grep organization /root/hashicat-aws/remote_backend.tf | cut -d '"' -f2)

# Check the token length
[[ 91 -eq $(echo $TOKEN | wc -m) ]] || fail-message "Oops, something's not right with your token."

# Does the user have a workspace configured
grep -q hashicat-aws /root/hashicat-aws/remote_backend.tf || fail-message "Oops, we couldn't find the hashicat-aws workspace in your remote_backend.tf config file. Try again."

# Does the user have an organization configured
grep -q YOURWORKSPACE /root/hashicat-aws/remote_backend.tf && fail-message "Oops, it looks like you haven't added your organization name to the remote_backend.tf file yet."

# Can we verify the organization exists in TFC?
# TODO - write this test with a curl command and maybe jq

# Can we verify the workspace exists in TFC?
# TODO - write this test with a curl command and maybe jq