#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-aws

ORG="${TFC_ORG:-instruqt-hashicat-aws-$RANDOM}"
TOKEN="${TFC_TOKEN:-REPLACETHISWITHYOURTOKEN}"

# Delete the workspace
curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request DELETE \
  https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-aws

# Delete the organization
curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request DELETE \
  https://app.terraform.io/api/v2/organizations/$ORG
