#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-aws

ORG="${TFC_ORG:-instruqt-hashicat-aws-$RANDOM}"
TOKEN="${TFC_TOKEN:-REPLACETHISWITHYOURTOKEN}"

# Configure the /root/.terraformrc file
cat <<-EOF > /root/.terraformrc
credentials "app.terraform.io" {
    token = "$TOKEN"
}
EOF

# Configure the remote_backend.tf file
cat <<-EOF > /root/hashicat-aws/remote_backend.tf
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "$ORG"
    workspaces {
      name = "hashicat-aws"
    }
  }
}
EOF

# Create an organization payload
cat <<-EOF > /tmp/create_org.json
{
  "data": {
    "type": "organizations",
    "attributes": {
      "name": "${ORG}",
      "email": "instruqt@hashicorp.com"
    }
  }
}
EOF

# Create a workspace payload
cat <<-EOF > /tmp/create_workspace.json
{
  "data": {
    "attributes": {
      "name": "hashicat-aws"
    },
    "type": "workspaces"
  }
}
EOF

# Create the organization
curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data @/tmp/create_org.json \
  https://app.terraform.io/api/v2/organizations

# Create a workspace
$ curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data @/tmp/create_workspace.json \
  https://app.terraform.io/api/v2/organizations/${ORG}/workspaces