#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/sentinel

#  Apply require-even-number.sentinel with the default value 1
sentinel apply require-even-number.sentinel

# Apply require-even-number.sentinel with the value 2
sentinel apply -param the_number=2 require-even-number.sentinel

# Edit the require-even-number test cases
sed -i 's/<an_odd_number>/5/g' /root/sentinel/test/require-even-number/fail.json
sed -i 's/<an_even_number>/4/g' /root/sentinel/test/require-even-number/pass.json

# Test the require-even-number.sentinel policy
sentinel test -run=number

exit 0
