#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

grep location /root/hashicat-azure/terraform.tfvars
EXITCODE=$?
if [ $EXITCODE -ne 1 ]; then
  fail-message "Oops, it looks like you haven't added your location to terraform.tfvars yet."
  exit 1
fi

exit 0
