#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-azure
if [ ! -f terraform.tfstate ]; then
  fail-message "Oops, it looks like you haven't run terraform apply yet."
fi

MYRG=$(cat terraform.tfstate | jq -r '.resources | .[].name')

if [ $MYRG != "myresourcegroup" ]; then
  fail-message "It looks like your resource group has not been built yet. Please try again."
fi

exit 0
