#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

[ -d /root/hashicat-gcp/.terraform ] || fail-message "Oops, you haven't run terraform init yet."

exit 0
