#!/bin/bash
cd /root/hashicat-aws
RESOURCES=$(cat terraform.tfstate | jq '.resources | .[]')

if [ ! -z $RESOURCES ]; then
  fail-message "Oops, looks like you still have some resources. Try running `terraform destroy` again."
  exit 1
fi