#!/bin/bash -l

set -e

# module-functions
mkdir -p /root/sentinel/common-functions/module-functions

cat <<-'EOF' > /root/sentinel/require-modules-from-pmr-b.sentinel
# This policy validates that all modules loaded directly by the
# root module are in the Private Module Registry (PMR) of a TFC
# organization.

# Import module-functions.sentinel as "modules"
<import_statement>

##### Parameters #####
# The address of the TFC or TFE server
param address default "app.terraform.io"

# The organization on the TFC or TFE server
param organization

# Call the validation function
modules_from_pmr = <function_call>

# Main rule
main = rule {
  modules_from_pmr
}
EOF

cat <<-'EOF' > /root/sentinel/common-functions/module-functions/module-functions.sentinel
# Functions that use the tfconfig import to restrict modules

##### Imports #####
import "tfconfig/v2" as tfconfig
import "strings"

##### Functions #####


EOF

mkdir -p /root/sentinel/test/require-modules-from-pmr-b

cat <<-'EOF' > /root/sentinel/test/require-modules-from-pmr-b/fail.json
{
  "param": {
    "organization": "Cloud-Operations"
  },
  "modules": {
    "module-functions": {
      "path": "../../common-functions/module-functions/module-functions.sentinel"
    }
  },
  "mock": {
    "tfconfig/v2": "mock-tfconfig-fail.sentinel"
  },
  "test": {
    "main": false
  }
}
EOF

cat <<-'EOF' > /root/sentinel/test/require-modules-from-pmr-b/mock-tfconfig-fail.sentinel

module_calls = {
  "module.windowsserver:os": {
    "config": {
      "vm_os_simple": {
        "references": [
          "var.vm_os_simple",
        ],
      },
    },
    "count":              {},
    "for_each":           {},
    "module_address":     "module.windowsserver",
    "name":               "os",
    "source":             "./os",
    "version_constraint": "",
  },
  "network": {
    "config": {
      "allow_ssh_traffic": {
        "constant_value": true,
      },
      "location": {
        "references": [
          "var.location",
        ],
      },
      "resource_group_name": {
        "references": [
          "var.windows_dns_prefix",
        ],
      },
    },
    "count":              {},
    "for_each":           {},
    "module_address":     "",
    "name":               "network",
    "source":             "Azure/network/azurerm",
    "version_constraint": "1.1.1",
  },
  "windowsserver": {
    "config": {
      "admin_password": {
        "references": [
          "var.admin_password",
        ],
      },
      "location": {
        "references": [
          "var.location",
        ],
      },
      "public_ip_dns": {
        "references": [
          "var.windows_dns_prefix",
        ],
      },
      "resource_group_name": {
        "references": [
          "var.windows_dns_prefix",
        ],
      },
      "storage_account_type": {
        "references": [
          "var.storage_account_type",
        ],
      },
      "vm_hostname": {
        "constant_value": "demohost",
      },
      "vm_os_simple": {
        "constant_value": "WindowsServer",
      },
      "vm_size": {
        "references": [
          "var.vm_size",
        ],
      },
      "vnet_subnet_id": {
        "references": [
          "module.network.vnet_subnets",
        ],
      },
    },
    "count":              {},
    "for_each":           {},
    "module_address":     "",
    "name":               "windowsserver",
    "source":             "Azure/compute/azurerm",
    "version_constraint": "1.1.6",
  },
}
EOF

cat <<-'EOF' > /root/sentinel/test/require-modules-from-pmr-b/mock-tfconfig-pass.sentinel
module_calls = {
  "module.windowsserver:os": {
    "config": {
      "vm_os_simple": {
        "references": [
          "var.vm_os_simple",
        ],
      },
    },
    "count":              {},
    "for_each":           {},
    "module_address":     "module.windowsserver",
    "name":               "os",
    "source":             "./os",
    "version_constraint": "",
  },
  "network": {
    "config": {
      "allow_ssh_traffic": {
        "constant_value": true,
      },
      "location": {
        "references": [
          "var.location",
        ],
      },
      "resource_group_name": {
        "references": [
          "var.windows_dns_prefix",
        ],
      },
    },
    "count":              {},
    "for_each":           {},
    "module_address":     "",
    "name":               "network",
    "source":             "app.terraform.io/Cloud-Operations/network/azurerm",
    "version_constraint": "1.1.1",
  },
  "windowsserver": {
    "config": {
      "admin_password": {
        "references": [
          "var.admin_password",
        ],
      },
      "location": {
        "references": [
          "var.location",
        ],
      },
      "public_ip_dns": {
        "references": [
          "var.windows_dns_prefix",
        ],
      },
      "resource_group_name": {
        "references": [
          "var.windows_dns_prefix",
        ],
      },
      "storage_account_type": {
        "references": [
          "var.storage_account_type",
        ],
      },
      "vm_hostname": {
        "constant_value": "demohost",
      },
      "vm_os_simple": {
        "constant_value": "WindowsServer",
      },
      "vm_size": {
        "references": [
          "var.vm_size",
        ],
      },
      "vnet_subnet_id": {
        "references": [
          "module.network.vnet_subnets",
        ],
      },
    },
    "count":              {},
    "for_each":           {},
    "module_address":     "",
    "name":               "windowsserver",
    "source":             "app.terraform.io/Cloud-Operations/compute/azurerm",
    "version_constraint": "1.1.6",
  },
}
EOF

cat <<-'EOF' > /root/sentinel/test/require-modules-from-pmr-b/pass.json
{
  "param": {
    "organization": "Cloud-Operations"
  },
  "modules": {
    "module-functions": {
      "path": "../../common-functions/module-functions/module-functions.sentinel"
    }
  },
  "mock": {
    "tfconfig/v2": "mock-tfconfig-pass.sentinel"
  },
  "test": {
    "main": true
  }
}
EOF

exit 0
