#!/bin/bash
grep location /root/hashicat-azure/terraform.tfvars 
EXITCODE=$?
if [ $EXITCODE -ne 0 ]; then
  fail-message "Oops, it looks like you haven't updated your location variable yet."
  exit 1
fi