#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-aws

# Make sure Terraform is not still running

if [ -f .terraform.tfstate.lock.info ]; then
    fail-message "Terraform is still running, please wait for it to finish."
fi

RESOURCES=$(cat terraform.tfstate | jq '.resources | .[]')

if [ ! -z "$RESOURCES" ]; then
  fail-message "Oops, looks like you still have some resources. Try running `terraform destroy` again."
fi

exit 0
