#!/bin/bash
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc
/bin/set-workdir /root/hashicat-azure

TOKEN=$(grep token /root/.terraformrc | cut -d '"' -f2)
ORG=$(grep organization /root/hashicat-azure/remote_backend.tf | cut -d '"' -f2)

# Test whether remote exec is enabled on the workspace.
REMOTE_EXEC_ENABLED=$(curl -s --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request GET https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-azure | jq .data.attributes.operations)

[[ $REMOTE_EXEC_ENABLED == true ]] || fail-message "Oops, it looks like remote exec is not enabled on your workspace."

# Does the workspace have an ARM_CLIENT_ID
CLIENT_ID=$(curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$ORG&filter%5Bworkspace%5D%5Bname%5D=hashicat-azure" | jq '.data | .[] | select(.attributes.key|test("ARM_CLIENT_ID")) | .attributes.sensitive')

# TODO: Fix this test
[[ $SECURE_ID == true ]] || fail-message "Uh oh, we didn't find an environment variable for your ARM_CLIENT_ID. Try again."

# TODO: Add tests for ARM_TENANT_ID, ARM_SUBSCRIPTION_ID, and ARM_CLIENT_SECRET

# Does the workspace have a prefix variable
curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$ORG&filter%5Bworkspace%5D%5Bname%5D=hashicat-azure" | grep -q "prefix" || fail-message "Oh dear, it looks like you don't have a Terraform variable called 'prefix' in your workspace."

# Does the workspace have a location variable
curl -s --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$ORG&filter%5Bworkspace%5D%5Bname%5D=hashicat-azure" | grep -q "location" || fail-message "Oh dear, it looks like you don't have a Terraform variable called 'location' in your workspace."