#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/hashicat-azure
OUTPUT=$(cat terraform.tfstate | jq -r .outputs.catapp_ip.value)

if [ -z $OUTPUT ]; then
  fail-message "We didn't find your catapp_ip output. Try again."
  exit 1
fi