#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

grep -q "region" /root/hashicat-gcp/terraform.tfvars || fail-message "Oops, it looks like you haven't added your region to terraform.tfvars yet."

exit 0
