version: "3"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/tfc-workstation-1-1-4
  shell: /bin/bash -l
  machine_type: n1-standard-1
azure_subscriptions:
- name: terraform
  roles:
  - Owner
