#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# Make sure Terraform is not still running

if [ -f .terraform.tfstate.lock.info ]; then
    fail-message "Terraform is still running, please wait for it to finish."
fi

# grep -q "terraform version" /root/.bash_history || fail-message "You haven't run terraform version yet."

# grep -q "terraform help" /root/.bash_history || fail-message "You haven't run terraform help yet."

exit 0
