#!/bin/bash

# Blow away the test workspace, hashicat-gcp if it exists
ORG=instruqt-circleci
TOKEN=$(cat /tmp/tfc_user_token)

# Delete the workspace. Might result in a 404 but that's OK as long as curl doesn't error out.
echo "Cleaning up the hashicat-gcp workspace..."
curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request DELETE https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-gcp

# fudge the git repo for testing; this one is already completed
cd /root
rm -rf hashicat-gcp
git clone https://github.com/scarolan/hashicat-gcp
GITDIR="/root/hashicat-gcp"

cd ${GITDIR}
echo -e "prefix = \"workshop\"" >> ${GITDIR}/terraform.tfvars
echo -e "\nregion = \"us-east-1\"" >> ${GITDIR}/terraform.tfvars

# Just the public DNS please
cat <<EOF > outputs.tf
# Outputs file
output "catapp_url" {
  value = "http://\${google_compute_instance.hashicat.public_dns}"
}
EOF