#!/bin/sh -l

set -e

grep -q "azure" restrict-vault-auth-methods.sentinel || fail-message "You have not added 'azure' to the allowed_methods list yet."

grep -q "kubernetes" restrict-vault-auth-methods.sentinel || fail-message "You have not added 'kubernetes' to the allowed_methods list yet."

grep -q "github" restrict-vault-auth-methods.sentinel || fail-message "You have not added 'github' to the allowed_methods list yet."

grep -q "approle" restrict-vault-auth-methods.sentinel || fail-message "You have not added 'approle' to the allowed_methods list yet."

grep -q "vault_auth_backend" restrict-vault-auth-methods.sentinel || fail-message "You have not replaced '<resource_type>' with 'vault_auth_backend' yet."

matches=$(grep -o type restrict-vault-auth-methods.sentinel | wc -l)
if [ ! "$matches" = "11" ]; then
    fail-message "You have not replaced '<attribute>' with 'type' yet."
fi

matches=$(grep -o allowed_methods restrict-vault-auth-methods.sentinel | wc -l)
if [ ! "$matches" = "2" ]; then
    fail-message "You have not replaced '<list>' with 'allowed_methods' yet."
fi

grep -q "sentinel test -run=vault -verbose" /root/.bash_history || grep -q "sentinel test -run=vault" /root/.bash_history || fail-message "You haven't tested the restrict-vault-auth-methods.sentinel policy against the test cases yet. Please run 'sentinel test -run=vault -verbose'"

sentinel test -run=vault
rc=$?
if [ $rc -ne 0 ]; then
    fail-message "Your policy did not pass both test cases. Please revise and test it again."
fi

exit 0
