#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/sentinel

# Edit the first version of the policy
sed -i 's/<data_source_type>/aws_acm_certificate/g' restrict-acm-certificate-domains-a.sentinel
sed -i 's/<attribute>/domain/g' restrict-acm-certificate-domains-a.sentinel
sed -i 's/<expression>/cert.values.domain/g' restrict-acm-certificate-domains-a.sentinel

# Test the first version of the policy
sentinel test -run=domains-a.sentinel -verbose

exit 0
