#!/bin/bash -l

cd /root/hashicat-$CLOUD_ENV

TOKEN=$(grep token /root/.terraform.d/credentials.tfrc.json | cut -d '"' -f4)

# We could delete the workspace, but don't really need to
# echo "Cleaning up the hashicat-$CLOUD_ENV workspace..."
# curl --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request DELETE https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-$CLOUD_ENV

# Let the user know we're done
echo "Cleanup process is complete."

exit 0
