#!/bin/bash -l
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# Checks the state file to make sure the student has added a tag.
cd /root/hashicat-aws

# Make sure Terraform is not still running

if [ -f .terraform.tfstate.lock.info ]; then
    fail-message "Terraform is still running, please wait for it to finish."
fi

# Check for tags
TAG=$(cat terraform.tfstate | jq -r '.resources[] | select(.type == "aws_vpc")| .instances[] | .attributes | .tags | .environment')

if [ "$TAG" != "Production" ]; then
   fail-message "You haven't added your Production environment tag yet."
fi

exit 0
