#!/bin/bash
# This is the setup script for the workstation container. Use it to set the stage for your terraform training, demo, or lab.

# Ensure environment variables are available for non-interactive logins
source /etc/profile.d/instruqt-env.sh
source /root/.bashrc

# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/local/bin/code-server --port 8443 --cert --auth none $(pwd)

[Install]
WantedBy=multi-user.target
EOF

# Start VSC
systemctl start code-server

# You can do anything! Clone an existing repo, or write some terraform from scratch.

# A few example repos to get you started:
# git clone https://github.com/hashicorp/hashicat-aws
# git clone https://github.com/hashicorp/hashicat-azure
# git clone https://github.com/hashicorp/hashicat-gcp

# Set the user's working directory with the set-workdir script, then in subsequent challenges the user will always start in that directory.
# /bin/set-workdir /root/my-git-repo

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc

# Drop the Terraform extension vsix file into /root
wget https://storage.googleapis.com/instruqt-hashicorp-tracks/terraform-shared/mauve.terraform-1.4.0.vsix -O /root/mauve.terraform-1.4.0.vsix