#!/bin/bash -l
set -e

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

touch /tmp/skip-check
# Create /tmp/skip-check to disable this check
# if [ -f /tmp/skip-check ]; then
# 	rm /tmp/skip-check
# 	exit 0
# fi
