#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

grep -q "terraform version" /root/.bash_history || fail-message "You haven't run terraform version yet. You can do it!"
grep -q "terraform help" /root/.bash_history || fail-message "You haven't run terraform help yet. We believe in you!"