#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd /root/hashicat-azure

# This needs to be fixed so it runs cleanly.
blast-radius --serve . > blastradius.log 2>&1 &

exit 0
